// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: serviciosStreaming.proto

package serviciosStreaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Artista       string                 `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Anio          int32                  `protobuf:"varint,5,opt,name=anio,proto3" json:"anio,omitempty"`
	Duracion      string                 `protobuf:"bytes,6,opt,name=duracion,proto3" json:"duracion,omitempty"`
	Genero        string                 `protobuf:"bytes,7,opt,name=genero,proto3" json:"genero,omitempty"`
	Idioma        string                 `protobuf:"bytes,8,opt,name=idioma,proto3" json:"idioma,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,9,opt,name=idUsuario,proto3" json:"idUsuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_serviciosStreaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *PeticionDTO) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

func (x *PeticionDTO) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *PeticionDTO) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *PeticionDTO) GetDuracion() string {
	if x != nil {
		return x.Duracion
	}
	return ""
}

func (x *PeticionDTO) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *PeticionDTO) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

func (x *PeticionDTO) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type FragmentoCancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentoCancion) Reset() {
	*x = FragmentoCancion{}
	mi := &file_serviciosStreaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentoCancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentoCancion) ProtoMessage() {}

func (x *FragmentoCancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosStreaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentoCancion.ProtoReflect.Descriptor instead.
func (*FragmentoCancion) Descriptor() ([]byte, []int) {
	return file_serviciosStreaming_proto_rawDescGZIP(), []int{1}
}

func (x *FragmentoCancion) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_serviciosStreaming_proto protoreflect.FileDescriptor

const file_serviciosStreaming_proto_rawDesc = "" +
	"\n" +
	"\x18serviciosStreaming.proto\x12\tservicios\"\xe3\x01\n" +
	"\vpeticionDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x18\n" +
	"\aartista\x18\x03 \x01(\tR\aartista\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x12\n" +
	"\x04anio\x18\x05 \x01(\x05R\x04anio\x12\x1a\n" +
	"\bduracion\x18\x06 \x01(\tR\bduracion\x12\x16\n" +
	"\x06genero\x18\a \x01(\tR\x06genero\x12\x16\n" +
	"\x06idioma\x18\b \x01(\tR\x06idioma\x12\x1c\n" +
	"\tidUsuario\x18\t \x01(\x05R\tidUsuario\"&\n" +
	"\x10fragmentoCancion\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2d\n" +
	"\fAudioService\x12T\n" +
	"\x1benviarCancionMedianteStream\x12\x16.servicios.peticionDTO\x1a\x1b.servicios.fragmentoCancion0\x01B\x15Z\x13/serviciosStreamingb\x06proto3"

var (
	file_serviciosStreaming_proto_rawDescOnce sync.Once
	file_serviciosStreaming_proto_rawDescData []byte
)

func file_serviciosStreaming_proto_rawDescGZIP() []byte {
	file_serviciosStreaming_proto_rawDescOnce.Do(func() {
		file_serviciosStreaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviciosStreaming_proto_rawDesc), len(file_serviciosStreaming_proto_rawDesc)))
	})
	return file_serviciosStreaming_proto_rawDescData
}

var file_serviciosStreaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serviciosStreaming_proto_goTypes = []any{
	(*PeticionDTO)(nil),      // 0: servicios.peticionDTO
	(*FragmentoCancion)(nil), // 1: servicios.fragmentoCancion
}
var file_serviciosStreaming_proto_depIdxs = []int32{
	0, // 0: servicios.AudioService.enviarCancionMedianteStream:input_type -> servicios.peticionDTO
	1, // 1: servicios.AudioService.enviarCancionMedianteStream:output_type -> servicios.fragmentoCancion
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serviciosStreaming_proto_init() }
func file_serviciosStreaming_proto_init() {
	if File_serviciosStreaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviciosStreaming_proto_rawDesc), len(file_serviciosStreaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciosStreaming_proto_goTypes,
		DependencyIndexes: file_serviciosStreaming_proto_depIdxs,
		MessageInfos:      file_serviciosStreaming_proto_msgTypes,
	}.Build()
	File_serviciosStreaming_proto = out.File
	file_serviciosStreaming_proto_goTypes = nil
	file_serviciosStreaming_proto_depIdxs = nil
}
